2023-06-27T18:39:25.199592+0300 ERROR [Errno 2] No such file or directory: 'C:\\xStorage\\Projects\\gsheets\\gsheets_key.json'
Traceback (most recent call last):

  File "C:\Users\Dima Tatarin\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000027C59D33060>
    └ <Thread(ThreadPoolExecutor-0_0, started 5020)>
  File "C:\Users\Dima Tatarin\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000027C59D32D40>
    └ <Thread(ThreadPoolExecutor-0_0, started 5020)>
  File "C:\Users\Dima Tatarin\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started 5020)>
    │    │        │    └ (<weakref at 0x0000027C7EE40220; to 'ThreadPoolExecutor' at 0x0000027C7ED255D0>, <_queue.SimpleQueue object at 0x0000027C7ED9...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started 5020)>
    │    └ <function _worker at 0x0000027C5F05D3A0>
    └ <Thread(ThreadPoolExecutor-0_0, started 5020)>
  File "C:\Users\Dima Tatarin\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x0000027C5F05D4E0>
    └ <concurrent.futures.thread._WorkItem object at 0x0000027C7ED111D0>
  File "C:\Users\Dima Tatarin\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x0000027C7ED111D0>
             │    │   │    └ (459471362, 'Dima Tatarin ᴵᵀ ᵖʳᵒᵈ ⁽ᵇᵒᵗˢ ⁻ ʷᵉᵇ ⁻ ᶜʳᵐ ⁻ ³ᵈ ⁻ ᶦᵒˢ ⁻ ᵘˣᵘᶦ ⁻ ᶜʳʸᵖᵗᵒ⁾', 'dimatatatarin')
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x0000027C7ED111D0>
             │    └ <function got_link at 0x0000027C5F05DBC0>
             └ <concurrent.futures.thread._WorkItem object at 0x0000027C7ED111D0>

> File "C:\xStorage\Projects\PrometeyBot\root\gsheets\main.py", line 35, in got_link
    gc = pygsheets.authorize(service_file=key_json)
         │         │                      └ 'C:\\xStorage\\Projects\\gsheets\\gsheets_key.json'
         │         └ <function authorize at 0x0000027C7ED36840>
         └ <module 'pygsheets' from 'C:\\xStorage\\Projects\\PrometeyBot\\venv\\Lib\\site-packages\\pygsheets\\__init__.py'>

  File "C:\xStorage\Projects\PrometeyBot\venv\Lib\site-packages\pygsheets\authorization.py", line 137, in authorize
    credentials = service_account.Credentials.from_service_account_file(service_account_file, scopes=scopes)
                  │               │           │                         │                            └ ('https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive')
                  │               │           │                         └ 'C:\\xStorage\\Projects\\gsheets\\gsheets_key.json'
                  │               │           └ <classmethod(<function Credentials.from_service_account_file at 0x0000027C5F356200>)>
                  │               └ <class 'google.oauth2.service_account.Credentials'>
                  └ <module 'google.oauth2.service_account' from 'C:\\xStorage\\Projects\\PrometeyBot\\venv\\Lib\\site-packages\\google\\oauth2\\...
  File "C:\xStorage\Projects\PrometeyBot\venv\Lib\site-packages\google\oauth2\service_account.py", line 241, in from_service_account_file
    info, signer = _service_account_info.from_filename(
                   │                     └ <function from_filename at 0x0000027C5F0A6A20>
                   └ <module 'google.auth._service_account_info' from 'C:\\xStorage\\Projects\\PrometeyBot\\venv\\Lib\\site-packages\\google\\auth...
  File "C:\xStorage\Projects\PrometeyBot\venv\Lib\site-packages\google\auth\_service_account_info.py", line 80, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
         │  │    └ 'C:\\xStorage\\Projects\\gsheets\\gsheets_key.json'
         │  └ <built-in function open>
         └ <module 'io' (frozen)>

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\xStorage\\Projects\\gsheets\\gsheets_key.json'
2023-06-27T22:29:28.883236+0300 ERROR 'NoneType' object has no attribute 'text'
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code

  File "C:\xStorage\Projects\PrometeyBot\root\tg\main.py", line 804, in <module>
    executor.start_polling(dispatcher=dp, skip_updates=True, on_startup=on_startup)
    │        │                        │                                 └ <function on_startup at 0x00000133626E4B80>
    │        │                        └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000013342935D10>
    │        └ <function start_polling at 0x00000133412E20C0>
    └ <module 'aiogram.utils.executor' from 'C:\\xStorage\\Projects\\PrometeyBot\\venv\\Lib\\site-packages\\aiogram\\utils\\executo...

  File "C:\xStorage\Projects\PrometeyBot\venv\Lib\site-packages\aiogram\utils\executor.py", line 45, in start_polling
    executor.start_polling(
    │        └ <function Executor.start_polling at 0x00000133412E2C00>
    └ <aiogram.utils.executor.Executor object at 0x00000133626E3690>
  File "C:\xStorage\Projects\PrometeyBot\venv\Lib\site-packages\aiogram\utils\executor.py", line 323, in start_polling
    loop.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001333F2A1F80>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Dima Tatarin\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Dima Tatarin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001333F1E3E20>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Dima Tatarin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001333F11DD00>
    └ <Handle <TaskStepMethWrapper object at 0x00000133626F0DC0>()>
  File "C:\Users\Dima Tatarin\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x00000133626F0DC0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x00000133626F0DC0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x00000133626F0DC0>()>
  File "C:\xStorage\Projects\PrometeyBot\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Update {"update_id": 56642122, "callback_query": {"id": "1973414474005432155", "from": {"id": 459471362, "is_bot": false, "...
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000013342935D10>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...
  File "C:\xStorage\Projects\PrometeyBot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
                 │    │                       │      │      └ <aiogram.types.fields.Field object at 0x0000013340FD1CD0>
                 │    │                       │      └ <Update {"update_id": 56642122, "callback_query": {"id": "1973414474005432155", "from": {"id": 459471362, "is_bot": false, "f...
                 │    │                       └ <function Handler.notify at 0x00000133411FA340>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x0000013342C26250>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000013342935D10>
  File "C:\xStorage\Projects\PrometeyBot\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<CallbackQuery {"id": "1973414474005432155", "from": {"id": 459471362, "is_bot": false, "first_name": "Dima Tatarin", "last_...
                     │           └ <function get_phone_number_for_payment_link at 0x00000133626D85E0>
                     └ Handler.HandlerObj(handler=<function get_phone_number_for_payment_link at 0x00000133626D85E0>, spec=FullArgSpec(args=['callba...

> File "C:\xStorage\Projects\PrometeyBot\root\tg\main.py", line 138, in get_phone_number_for_payment_link
    GET_PHONE_NUMBER_MESSAGE = session.query(models.Text).filter(models.Text.id == 92).first().text
                               │       │     │      │            │      │    └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x00000133416D9760>
                               │       │     │      │            │      └ <class 'root.db.models.Text'>
                               │       │     │      │            └ <module 'root.db.models' from 'C:\\xStorage\\Projects\\PrometeyBot\\root\\db\\models.py'>
                               │       │     │      └ <class 'root.db.models.Text'>
                               │       │     └ <module 'root.db.models' from 'C:\\xStorage\\Projects\\PrometeyBot\\root\\db\\models.py'>
                               │       └ <function Session.query at 0x00000133415D2AC0>
                               └ <sqlalchemy.orm.session.Session object at 0x0000013362717890>

AttributeError: 'NoneType' object has no attribute 'text'
2023-06-27T22:30:46.760100+0300 ERROR 'NoneType' object has no attribute 'text'
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code

  File "C:\xStorage\Projects\PrometeyBot\root\tg\main.py", line 804, in <module>
    executor.start_polling(dispatcher=dp, skip_updates=True, on_startup=on_startup)
    │        │                        │                                 └ <function on_startup at 0x00000133626E4B80>
    │        │                        └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000013342935D10>
    │        └ <function start_polling at 0x00000133412E20C0>
    └ <module 'aiogram.utils.executor' from 'C:\\xStorage\\Projects\\PrometeyBot\\venv\\Lib\\site-packages\\aiogram\\utils\\executo...

  File "C:\xStorage\Projects\PrometeyBot\venv\Lib\site-packages\aiogram\utils\executor.py", line 45, in start_polling
    executor.start_polling(
    │        └ <function Executor.start_polling at 0x00000133412E2C00>
    └ <aiogram.utils.executor.Executor object at 0x00000133626E3690>
  File "C:\xStorage\Projects\PrometeyBot\venv\Lib\site-packages\aiogram\utils\executor.py", line 323, in start_polling
    loop.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001333F2A1F80>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Dima Tatarin\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Dima Tatarin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001333F1E3E20>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Dima Tatarin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001333F11DD00>
    └ <Handle <TaskStepMethWrapper object at 0x00000133626F1D50>()>
  File "C:\Users\Dima Tatarin\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x00000133626F1D50>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x00000133626F1D50>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x00000133626F1D50>()>
  File "C:\xStorage\Projects\PrometeyBot\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Update {"update_id": 56642123, "callback_query": {"id": "1973414474439543248", "from": {"id": 459471362, "is_bot": false, "...
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000013342935D10>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...
  File "C:\xStorage\Projects\PrometeyBot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
                 │    │                       │      │      └ <aiogram.types.fields.Field object at 0x0000013340FD1CD0>
                 │    │                       │      └ <Update {"update_id": 56642123, "callback_query": {"id": "1973414474439543248", "from": {"id": 459471362, "is_bot": false, "f...
                 │    │                       └ <function Handler.notify at 0x00000133411FA340>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x0000013342C26250>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000013342935D10>
  File "C:\xStorage\Projects\PrometeyBot\venv\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<CallbackQuery {"id": "1973414474439543248", "from": {"id": 459471362, "is_bot": false, "first_name": "Dima Tatarin", "last_...
                     │           └ <function get_phone_number_for_payment_link at 0x00000133626D85E0>
                     └ Handler.HandlerObj(handler=<function get_phone_number_for_payment_link at 0x00000133626D85E0>, spec=FullArgSpec(args=['callba...

> File "C:\xStorage\Projects\PrometeyBot\root\tg\main.py", line 138, in get_phone_number_for_payment_link
    GET_PHONE_NUMBER_MESSAGE = session.query(models.Text).filter(models.Text.id == 92).first().text
                               │       │     │      │            │      │    └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x00000133416D9760>
                               │       │     │      │            │      └ <class 'root.db.models.Text'>
                               │       │     │      │            └ <module 'root.db.models' from 'C:\\xStorage\\Projects\\PrometeyBot\\root\\db\\models.py'>
                               │       │     │      └ <class 'root.db.models.Text'>
                               │       │     └ <module 'root.db.models' from 'C:\\xStorage\\Projects\\PrometeyBot\\root\\db\\models.py'>
                               │       └ <function Session.query at 0x00000133415D2AC0>
                               └ <sqlalchemy.orm.session.Session object at 0x00000133625BDA50>

AttributeError: 'NoneType' object has no attribute 'text'
